# Generated by Django 5.2.11 on 2026-02-11 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('password_enabled', models.BooleanField(default=False)),
                ('password_hash', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('theme_id', models.CharField(blank=True, default='colorful_pop_v1', max_length=80)),
                ('theme_settings', models.JSONField(blank=True, default=dict)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('renderer', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pixelpopup_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=120)),
                ('client_contact', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('occasion', models.CharField(blank=True, default='', max_length=80)),
                ('brief', models.TextField(blank=True, default='')),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('price_quote', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('quoted', 'Quoted'), ('waiting_payment', 'Waiting for payment'), ('paid', 'Paid'), ('in_progress', 'In progress'), ('for_review', 'For review'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('notes_internal', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pixelpopup_assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='pixelpopup.page')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('gif', 'GIF'), ('other', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to='pixelpopup/assets/%Y/%m/')),
                ('mime', models.CharField(blank=True, default='', max_length=100)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='pixelpopup.page')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('method', models.CharField(choices=[('gcash', 'GCash'), ('maya', 'Maya'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='gcash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reference_code', models.CharField(blank=True, default='', max_length=120)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='pixelpopup/receipts/%Y/%m/')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pixelpopup.clientrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('type', models.CharField(choices=[('motion', 'Motion'), ('question', 'Question'), ('choice', 'Choice'), ('timeline', 'Timeline'), ('letter', 'Letter'), ('map', 'Map'), ('exploration', 'Exploration'), ('finale', 'Finale')], max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('renderer', models.JSONField(blank=True, null=True)),
                ('theme_override_id', models.CharField(blank=True, default='', max_length=80)),
                ('theme_override_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='pixelpopup.page')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='uniq_scene_key_per_page')],
            },
        ),
    ]
