# Generated by Django 5.2.14 on 2026-08-18 00:50

import django.db.models.deletion
import pixelpopup.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelpopup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'article categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=240)),
                ('subject_template', models.CharField(blank=True, default='Application for {job_title} at {company_name}', max_length=200)),
                ('opening_template', models.TextField()),
                ('body_template', models.TextField()),
                ('closing_template', models.TextField()),
                ('default_highlights', models.JSONField(blank=True, default=list, validators=[pixelpopup.models.validate_list_value])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('headline', models.CharField(max_length=180)),
                ('professional_summary', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('website_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('resume_url', models.URLField(blank=True, default='')),
                ('signature', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('excerpt', models.CharField(max_length=320)),
                ('content', models.TextField()),
                ('content_format', models.CharField(choices=[('markdown', 'Markdown'), ('plain', 'Plain text')], default='markdown', max_length=12)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='portfolio/articles/%Y/%m/')),
                ('cover_image_alt', models.CharField(blank=True, default='', max_length=180)),
                ('seo_title', models.CharField(blank=True, default='', max_length=70)),
                ('seo_description', models.CharField(blank=True, default='', max_length=170)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='pixelpopup.articlecategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='pixelpopup.articletag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('company_name', models.CharField(max_length=160)),
                ('company_website', models.URLField(blank=True, default='')),
                ('job_title', models.CharField(max_length=160)),
                ('job_url', models.URLField(blank=True, default='')),
                ('recipient_name', models.CharField(blank=True, default='Hiring Manager', max_length=120)),
                ('recipient_title', models.CharField(blank=True, default='', max_length=120)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('source', models.CharField(blank=True, default='', max_length=80)),
                ('job_description', models.TextField(blank=True, default='')),
                ('notes_private', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('subject', models.CharField(max_length=200)),
                ('opening', models.TextField()),
                ('body', models.TextField()),
                ('closing', models.TextField()),
                ('highlights', models.JSONField(blank=True, default=list, validators=[pixelpopup.models.validate_list_value])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letters', to='pixelpopup.coverlettertemplate')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='pixelpopup.jobapplication')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cover_letters', to='pixelpopup.professionalprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('application', 'version'), name='uniq_cover_letter_version_per_application')],
            },
        ),
    ]
