import { Award, BookOpen, BriefcaseBusiness, Code2, FilePenLine, FolderGit2, GraduationCap, HeartHandshake, Languages, Link2, Target, Trophy, UserRound, Users } from "lucide-react";

// Templates provide structure, never invented experience or qualifications.
export const resumeSectionTemplates = [
  { value: "custom", label: "Custom section", icon: FilePenLine, description: "Choose your own heading and content.", content: "" },
  { value: "profile", label: "Profile", icon: UserRound, description: "A concise, source-backed professional introduction.", content: "[Describe your current role, strongest expertise and the value you bring. Use only experience you can support.]" },
  { value: "strengths", label: "Core strength", icon: Target, description: "Your strongest capabilities, grouped by area.", content: "- **[Capability area]:** [Your strengths and supporting experience]\n- **[Capability area]:** [Your strengths and supporting experience]" },
  { value: "skills", label: "Skills & specialization", icon: Code2, description: "Group genuine skills by technical specialization.", content: "- **Frontend:** [Tools and frameworks you use]\n- **Backend:** [Languages, frameworks and APIs you use]\n- **Infrastructure:** [Deployment tools you have used]\n- **Specializations:** [Your demonstrated areas of expertise]" },
  { value: "experience", label: "Professional experience", icon: BriefcaseBusiness, description: "Roles, accurate dates and achievement-focused bullets.", content: "### [Job title], [Company]\n[Actual start date] – [Actual end date or Present]\n\n- [What you delivered or improved, with a real outcome]\n- [Your responsibilities and contribution]\n\n**Technologies used:** [Tools you actually used]" },
  { value: "projects", label: "Project involvement", icon: FolderGit2, description: "Projects, your contribution and supported outcomes.", content: "### [Project name]\n[Actual date, if relevant]\n\n[Project purpose and your role]\n\n- [What you built, improved or solved]\n\n**Technologies used:** [Tools you actually used]\n\n[Project link, if public]" },
  { value: "education", label: "Education history", icon: GraduationCap, description: "Qualifications, institutions and accurate dates.", content: "### [Qualification], [Institution]\n[Actual start date] – [Actual end date]\n\n[Relevant honors or coursework, if applicable]" },
  { value: "certifications", label: "Certifications", icon: Award, description: "Earned credentials and their issuers.", content: "### [Certification], [Issuer]\n[Actual date earned]\n\n[Credential ID or verification link, if available]\n[Expiry date, if applicable]" },
  { value: "languages", label: "Languages", icon: Languages, description: "Languages and honest proficiency descriptions.", content: "- **[Language]:** [Your actual proficiency]\n- **[Language]:** [Your actual proficiency]" },
  { value: "awards", label: "Awards", icon: Trophy, description: "Verified recognition, issuer and date.", content: "### [Award], [Organization]\n[Actual date]\n\n[What the award recognized]" },
  { value: "volunteer", label: "Volunteer experience", icon: HeartHandshake, description: "Volunteer roles and contributions.", content: "### [Role], [Organization]\n[Actual dates]\n\n- [Your contribution and supported outcome]" },
  { value: "publications", label: "Publications", icon: BookOpen, description: "Published writing, research or talks.", content: "### [Title]\n[Publication or event] · [Actual date]\n\n[Your contribution]\n[Public link, if available]" },
  { value: "links", label: "Links", icon: Link2, description: "Portfolio, GitHub and professional profiles.", content: "- [Portfolio](https://your-portfolio.example)\n- [GitHub](https://github.com/your-username)\n- [LinkedIn](https://www.linkedin.com/in/your-profile)" },
  { value: "references", label: "References", icon: Users, description: "Only include contacts with permission to share them.", content: "[Reference name]\n[Role and organization]\n[Contact details shared with permission]" },
];
