import { createElement } from "react";
import {
  Accessibility,
  Activity,
  BadgeCheck,
  BarChart3,
  Blocks,
  Bot,
  BookOpen,
  ClipboardCheck,
  Code2,
  Cuboid,
  Database,
  Download,
  FileCheck2,
  Gauge,
  GitPullRequest,
  Globe2,
  History,
  LayoutTemplate,
  ListChecks,
  Monitor,
  MonitorCog,
  PackageCheck,
  Palette,
  PanelsTopLeft,
  Plug,
  Rocket,
  Route,
  Search,
  SearchCheck,
  Server,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Tags,
  Workflow,
  Wrench,
} from "lucide-react";

const icons = {
  accessibility: Accessibility,
  activity: Activity,
  "badge-check": BadgeCheck,
  blocks: Blocks,
  bot: Bot,
  "book-open": BookOpen,
  "chart-no-axes-combined": BarChart3,
  "clipboard-check": ClipboardCheck,
  code: Code2,
  "box-3d": Cuboid,
  database: Database,
  "file-check": FileCheck2,
  gauge: Gauge,
  "git-pull-request": GitPullRequest,
  globe: Globe2,
  history: History,
  import: Download,
  layout: LayoutTemplate,
  "list-checks": ListChecks,
  monitor: Monitor,
  "monitor-cog": MonitorCog,
  "package-check": PackageCheck,
  palette: Palette,
  panels: PanelsTopLeft,
  plug: Plug,
  rocket: Rocket,
  route: Route,
  search: Search,
  "search-check": SearchCheck,
  server: Server,
  shield: Shield,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  tags: Tags,
  workflow: Workflow,
  wrench: Wrench,
};

export default function AstaServiceIcon({ name, ...props }) {
  return createElement(icons[name] || Blocks, props);
}
