export const portfolioTechnologyCatalog = {
  threejs: {
    name: "Three.js",
    shortLabel: "3D",
    icon: "/portfolio/tech/three.svg",
    summary: "A JavaScript library for rendering interactive 3D scenes in the browser with WebGL.",
    personalUse: "I use it for service heroes, product storytelling, spatial interfaces, and focused interactive demonstrations.",
    bestFor: "Product visualization, configurators, technical storytelling, and memorable campaign experiences.",
  },
  webgl: {
    name: "WebGL",
    shortLabel: "GL",
    icon: "/portfolio/tech/webgl.svg",
    summary: "The browser graphics API that lets Three.js render hardware-accelerated 2D and 3D visuals.",
    personalUse: "I account for device limits, pixel ratio, render cost, visibility, cleanup, and graceful fallbacks.",
    bestFor: "High-performance browser graphics when a normal DOM interface cannot express the experience clearly.",
  },
  react: {
    name: "React",
    shortLabel: "R",
    icon: "/portfolio/tech/react.svg",
    summary: "A component-based JavaScript library for building interactive user interfaces.",
    personalUse: "I use React for reusable product surfaces, complex interaction states, and frontend architecture that teams can extend.",
    bestFor: "Interactive applications, component systems, dashboards, and products with substantial client-side behavior.",
  },
  vue: {
    name: "Vue",
    shortLabel: "V",
    icon: "/portfolio/tech/vue.svg",
    summary: "A progressive JavaScript framework for building approachable, reactive web interfaces.",
    personalUse: "I use Vue for maintainable product UI and for improving established Vue codebases without forcing unnecessary rewrites.",
    bestFor: "Products that value readable components, incremental adoption, and a productive development experience.",
  },
  nuxt: {
    name: "Nuxt",
    shortLabel: "N",
    icon: "/portfolio/tech/nuxt.svg",
    summary: "A Vue framework for server rendering, routing, data fetching, and production web delivery.",
    personalUse: "I use Nuxt for crawlable product pages, shared application structure, and multi-surface platforms such as DineEase.",
    bestFor: "Vue products that need SEO, server rendering, structured routing, and an opinionated application foundation.",
  },
  typescript: {
    name: "TypeScript",
    shortLabel: "TS",
    icon: "/portfolio/tech/typescript.svg",
    summary: "JavaScript with static types for clearer contracts and safer changes across a codebase.",
    personalUse: "I use types to make component, API, and domain boundaries easier to understand during implementation and review.",
    bestFor: "Growing frontend and Node.js products where multiple contributors need dependable interfaces.",
  },
  tailwind: {
    name: "Tailwind CSS",
    shortLabel: "TW",
    icon: "/portfolio/tech/tailwind.svg",
    summary: "A utility-first CSS framework for composing responsive interfaces from consistent design tokens.",
    personalUse: "I use Tailwind to keep layout and state styling close to components while preserving an intentional design system.",
    bestFor: "Fast product UI delivery where consistency, responsive behavior, and maintainable styling matter.",
  },
  figma: {
    name: "Figma",
    shortLabel: "F",
    icon: "/portfolio/tech/figma.svg",
    summary: "A collaborative interface design tool for flows, components, prototypes, and developer handoff.",
    personalUse: "I use Figma to clarify hierarchy, responsive behavior, reusable patterns, and implementation details before code grows expensive.",
    bestFor: "Product design, design systems, stakeholder review, prototyping, and engineering handoff.",
  },
  canva: {
    name: "Canva",
    shortLabel: "CA",
    summary: "A visual design platform for quickly producing brand-aligned marketing and content assets.",
    personalUse: "I use Canva when a team needs practical social, presentation, campaign, or lightweight brand assets without a heavy design workflow.",
    bestFor: "Fast marketing assets, reusable templates, presentations, and content teams that need safe editing controls.",
  },
  hotjar: {
    name: "Hotjar",
    shortLabel: "HJ",
    icon: "/portfolio/tech/hotjar.svg",
    summary: "A behavior analytics tool for heatmaps, recordings, feedback, and surveys.",
    personalUse: "I use Hotjar to investigate where visitors hesitate, miss content, or abandon an important journey.",
    bestFor: "Explaining user behavior that page-view and conversion metrics cannot explain on their own.",
  },
  posthog: {
    name: "PostHog",
    shortLabel: "PH",
    summary: "A product analytics platform for events, funnels, retention, paths, session replay, and experiments.",
    personalUse: "I use PostHog to connect interface changes to real product behavior and to inspect the journeys behind conversion or drop-off.",
    bestFor: "Product teams that need event analytics, qualitative replay, funnels, and feature evaluation in one workflow.",
  },
  django: {
    name: "Django",
    shortLabel: "DJ",
    icon: "/portfolio/tech/django.svg",
    summary: "A Python web framework with routing, ORM, migrations, authentication, security defaults, and administration.",
    personalUse: "I use Django for business logic, operational systems, content models, APIs, permissions, and dependable admin workflows.",
    bestFor: "Data-backed products that need mature backend conventions, structured operations, and fast domain delivery.",
  },
  python: {
    name: "Python",
    shortLabel: "PY",
    icon: "/portfolio/tech/python.svg",
    summary: "A readable general-purpose language used across backend systems, automation, data work, and AI integration.",
    personalUse: "I use Python for Django products, scripts, reporting, data processing, and reliable automation around business workflows.",
    bestFor: "Backend development, automation, integrations, data processing, and AI-assisted product features.",
  },
  node: {
    name: "Node.js",
    shortLabel: "JS",
    icon: "/portfolio/tech/node.svg",
    summary: "A JavaScript runtime for servers, APIs, build tooling, and automation outside the browser.",
    personalUse: "I use Node.js for lightweight services, email endpoints, frontend tooling, integrations, and JavaScript-first application backends.",
    bestFor: "API services, real-time systems, build tools, and teams sharing JavaScript across frontend and backend.",
  },
  postgresql: {
    name: "PostgreSQL",
    shortLabel: "PG",
    icon: "/portfolio/tech/postgresql.svg",
    summary: "A relational database for structured data, transactional integrity, indexing, and advanced queries.",
    personalUse: "I use PostgreSQL behind Django and product platforms where relationships, reporting, and correctness matter.",
    bestFor: "Operational products, commerce, reporting, and systems that need reliable relational data.",
  },
  strapi: {
    name: "Strapi",
    shortLabel: "ST",
    icon: "/portfolio/tech/strapi.svg",
    summary: "A headless CMS that exposes structured content through APIs while giving editors an administration interface.",
    personalUse: "I use headless CMS patterns when content needs to serve multiple frontend surfaces without coupling publishing to one template system.",
    bestFor: "Structured publishing, reusable content, multi-channel delivery, and frontend-controlled experiences.",
  },
  lighthouse: {
    name: "Lighthouse",
    shortLabel: "LH",
    summary: "Chrome's automated lab audit for performance, accessibility, best practices, and basic SEO checks.",
    personalUse: "I use Lighthouse to locate measurable frontend bottlenecks, then confirm whether the fix improves the real production experience.",
    bestFor: "Repeatable lab diagnostics and a focused starting point for performance and accessibility investigation.",
  },
  pagespeed: {
    name: "PageSpeed Insights",
    shortLabel: "PSI",
    summary: "A Google tool combining Lighthouse diagnostics with Chrome field data when enough real-user data is available.",
    personalUse: "I compare lab findings with field Core Web Vitals so optimization targets the pages and metrics users actually experience.",
    bestFor: "Prioritizing Core Web Vitals work and separating local test results from production user data.",
  },
  searchConsole: {
    name: "Google Search Console",
    shortLabel: "GSC",
    summary: "Google's reporting surface for search queries, pages, clicks, impressions, indexing, and crawl diagnostics.",
    personalUse: "I use Search Console to connect technical changes and content structure to discovery, indexation, and useful search journeys.",
    bestFor: "Diagnosing indexing issues, monitoring search visibility, and finding which pages and queries deserve attention.",
  },
  ahrefs: {
    name: "Ahrefs",
    shortLabel: "AH",
    summary: "An SEO research platform for backlinks, keywords, competitors, content gaps, and crawl analysis.",
    personalUse: "I use Ahrefs for external search context, then validate priorities against first-party Search Console and product analytics data.",
    bestFor: "Competitive research, backlink review, keyword discovery, content gaps, and technical crawl investigation.",
  },
  openai: {
    name: "OpenAI API",
    shortLabel: "AI",
    summary: "A model API for text, structured output, tool calling, retrieval, images, audio, and multimodal workflows.",
    personalUse: "I use it inside bounded workflows with explicit inputs, schemas, review points, failure handling, and cost awareness.",
    bestFor: "AI-assisted features that need structured responses, tool use, retrieval, or multimodal capabilities.",
  },
  claude: {
    name: "Claude",
    shortLabel: "CL",
    summary: "Anthropic's model family for long-context analysis, structured tasks, document work, and tool use.",
    personalUse: "I use Claude for document-centered workflows, implementation support, analysis, and tasks that benefit from long context.",
    bestFor: "Document-heavy automation, analysis, coding support, and controlled tool workflows.",
  },
  n8n: {
    name: "n8n",
    shortLabel: "n8n",
    summary: "A workflow automation platform that connects triggers, APIs, data transformations, approvals, and business tools.",
    personalUse: "I use workflow orchestration when a process needs visible steps and integrations without turning every handoff into custom backend code.",
    bestFor: "Event-driven automation, system synchronization, notifications, approvals, and operational workflows.",
  },
  docker: {
    name: "Docker",
    shortLabel: "DK",
    icon: "/portfolio/tech/docker.svg",
    summary: "A container platform for packaging applications and dependencies into repeatable runtime environments.",
    personalUse: "I use Docker to make local, staging, and production environments more predictable across frontend and backend services.",
    bestFor: "Repeatable application delivery, service isolation, CI pipelines, and portable deployment workflows.",
  },
  nginx: {
    name: "Nginx",
    shortLabel: "NX",
    icon: "/portfolio/tech/nginx.svg",
    summary: "A web server and reverse proxy commonly used for TLS termination, static files, routing, and upstream traffic.",
    personalUse: "I use Nginx in practical Django and Node deployments where requests, static assets, and application processes need clear boundaries.",
    bestFor: "Reverse proxying, HTTPS delivery, static assets, caching, and routing traffic to application servers.",
  },
  aws: {
    name: "AWS",
    shortLabel: "AWS",
    icon: "/portfolio/tech/aws.svg",
    summary: "A cloud platform offering compute, storage, databases, networking, monitoring, and managed application services.",
    personalUse: "I use AWS building blocks around the product's actual operating needs rather than adding infrastructure for appearance.",
    bestFor: "Products that need configurable cloud infrastructure, managed data services, storage, and operational control.",
  },
  sentry: {
    name: "Sentry",
    shortLabel: "SE",
    summary: "An application monitoring platform for errors, traces, releases, environments, and performance issues.",
    personalUse: "I use error context and release markers to isolate failures, understand impact, and verify whether a repair reaches production.",
    bestFor: "Production debugging, release health, frontend and backend errors, and performance investigation.",
  },
  git: {
    name: "Git",
    shortLabel: "GIT",
    icon: "/portfolio/tech/git.svg",
    summary: "A distributed version control system for tracking code history, collaboration, review, and safe release workflows.",
    personalUse: "I use focused branches, readable commits, reviews, and reversible changes to keep delivery understandable across a team.",
    bestFor: "Every collaborative software project that needs traceable changes and controlled integration.",
  },
};

export const portfolioServiceCatalog = [
  {
    id: "threejs-development",
    slug: "threejs-development",
    title: "Three.js Development",
    shortTitle: "Interactive 3D",
    summary: "Purposeful browser-based 3D for product stories, visualization, configurators, and interactive campaigns.",
    featured: true,
    icon: "box",
    overview: {
      title: "3D that earns its place.",
      paragraphs: [
        "I plan the scene around what a visitor needs to inspect, understand, or configure. The interface, loading strategy, camera, controls, and fallback are part of the same product decision.",
        "My portfolio and ASTA service pages demonstrate how I isolate Three.js from the main interface, pause work outside the viewport, and keep the page useful when motion or WebGL is unavailable.",
      ],
    },
    inclusions: [
      ["Scene direction", "Define the visual purpose, interaction, framing, and fallback before building geometry."],
      ["Three.js implementation", "Build the scene, materials, lighting, camera, controls, and lifecycle cleanup."],
      ["Product integration", "Connect 3D state to React or Vue interfaces, data, analytics, and application actions."],
      ["Model review", "Assess GLB or GLTF assets, texture weight, topology, and browser suitability."],
      ["Performance work", "Control pixel ratio, rendering cost, visibility, loading, and mobile scene detail."],
      ["Accessible fallback", "Preserve the message and primary action without relying on animation or WebGL."],
    ],
    technologies: ["threejs", "webgl", "react", "vue", "typescript", "lighthouse"],
    faqs: [
      ["When would you recommend Three.js?", "I recommend it when spatial interaction helps people understand, inspect, or configure something. If a normal image or video communicates the same idea better, I will say so."],
      ["Can you use an existing 3D model?", "Yes. I first review format, materials, textures, topology, animation, and file size, then explain what needs optimization before it reaches the browser."],
      ["Will it work on mobile?", "I design a separate mobile framing and performance budget. The scene can simplify while the surrounding content and action remain complete."],
      ["Can this fit an existing React or Vue app?", "Yes. I keep the renderer in a focused component with explicit inputs, cleanup, visibility controls, and a stable boundary from the rest of the application."],
    ],
  },
  {
    id: "ai-automation",
    slug: "ai-automation",
    title: "AI Automation",
    shortTitle: "AI workflows",
    summary: "AI-assisted product and business workflows with clear inputs, tools, review points, and recovery paths.",
    featured: true,
    icon: "bot",
    overview: {
      title: "AI workflows with clear boundaries.",
      paragraphs: [
        "I start with the task, available data, repeated decisions, exceptions, and the person who owns the result. This keeps the implementation grounded in real work rather than an isolated chatbot demo.",
        "The resulting workflow can retrieve approved context, call tools, return structured output, request human review, and expose failures that need correction.",
      ],
    },
    inclusions: [
      ["Workflow discovery", "Map the current process, inputs, exceptions, risks, and human ownership."],
      ["Provider selection", "Choose a model around the task, context, latency, cost, and data constraints."],
      ["Tool integration", "Connect approved APIs and systems through explicit actions and permissions."],
      ["Structured outputs", "Use predictable response schemas that software can validate before acting."],
      ["Human review", "Keep approval and escalation visible where model output carries business risk."],
      ["Evaluation", "Track quality, failure cases, latency, and cost so the workflow can improve."],
    ],
    technologies: ["openai", "claude", "python", "node", "n8n", "django"],
    faqs: [
      ["What is a good first automation project?", "A focused workflow with repeated effort, clear inputs, a reviewable output, and an owner is usually a better start than a company-wide assistant."],
      ["Will you recommend a specific AI provider?", "I compare the task, context window, tool needs, privacy constraints, latency, and cost. The provider should follow the workflow, not the other way around."],
      ["How do you reduce incorrect output?", "I constrain the task, validate structure, ground responses where appropriate, define escalation, and keep important decisions reviewable."],
      ["Can this connect to our current tools?", "Usually, yes, when the tools offer suitable APIs and permissions. I document each action, data boundary, error path, and retry behavior."],
    ],
  },
  {
    id: "website-design",
    slug: "website-design",
    title: "Website Design",
    shortTitle: "Product and web design",
    summary: "Clear, responsive interfaces shaped around your brand, content, customer journey, and implementation reality.",
    icon: "palette",
    overview: {
      title: "Design that makes decisions easier.",
      paragraphs: [
        "I organize content, navigation, actions, and responsive behavior around the questions a visitor actually brings to the page.",
        "Because I also build interfaces, the design accounts for real content, component reuse, edge states, accessibility, and the handoff required for production delivery.",
      ],
    },
    inclusions: [
      ["Journey mapping", "Clarify audience questions, page purpose, decision points, and primary actions."],
      ["Information architecture", "Organize navigation and content so the important path stays understandable."],
      ["Responsive design", "Plan desktop, tablet, and mobile behavior as one coherent system."],
      ["Design system", "Define reusable typography, color, spacing, components, and interaction states."],
      ["Prototype and review", "Make key journeys reviewable before expensive implementation decisions settle."],
      ["Build-ready guidance", "Document component behavior, content needs, states, and implementation details."],
    ],
    technologies: ["figma", "canva", "tailwind", "react", "hotjar", "posthog"],
    faqs: [
      ["Do you only design developer-focused websites?", "No. I design around the audience and business goal, then choose an expression that fits the brand instead of applying one technical style everywhere."],
      ["Can you also build the design?", "Yes. Design and development can stay in one engagement, which helps preserve responsive behavior, accessibility, and component intent through implementation."],
      ["Where does Canva fit?", "I use Canva for practical brand and marketing assets when a team needs editable templates. Figma remains stronger for detailed interface systems and product flows."],
      ["What do you need before starting?", "A clear business goal, target audience, available content, brand material, current pain points, and any useful analytics or customer feedback."],
    ],
  },
  {
    id: "website-development",
    slug: "website-development",
    title: "Website Development",
    shortTitle: "Full-stack web delivery",
    summary: "Maintainable websites and web applications connected to real data, workflows, APIs, and release needs.",
    icon: "code",
    overview: {
      title: "Build now. Keep room to grow.",
      paragraphs: [
        "I translate requirements into responsive interfaces, clear component boundaries, dependable APIs, data models, and release-ready application code.",
        "My work is frontend-led, but I am comfortable owning the backend and infrastructure boundaries needed to deliver a complete web product.",
      ],
    },
    inclusions: [
      ["Technical planning", "Define scope, architecture, interfaces, dependencies, and delivery sequence."],
      ["Frontend engineering", "Build accessible responsive interfaces for real data and interaction states."],
      ["Backend and APIs", "Implement domain logic, authentication, permissions, data access, and integrations."],
      ["Database design", "Model relationships and queries around the product's operational needs."],
      ["Quality controls", "Review critical journeys, browser behavior, failure states, and release risks."],
      ["Release handoff", "Document environments, configuration, deployment, and ongoing ownership."],
    ],
    technologies: ["react", "vue", "nuxt", "django", "node", "postgresql", "docker"],
    faqs: [
      ["Can you work with an existing codebase?", "Yes. I begin with a focused review of the architecture, current conventions, risks, and the safest boundaries for change."],
      ["Which stack do you prefer?", "I work most often with React, Vue, Nuxt, Django, Python, Node.js, and PostgreSQL. I select from the product and team context rather than forcing a fixed package."],
      ["Do I need complete designs first?", "No. I can include interface design, work from an existing design system, or collaborate with your designer while keeping engineering constraints visible."],
      ["Can you continue after launch?", "Yes. Ongoing improvements, debugging, performance work, and technical ownership can be scoped around the product's release cadence."],
    ],
  },
  {
    id: "cms-solutions",
    slug: "cms-solutions",
    title: "CMS Solutions",
    shortTitle: "Content systems",
    summary: "Structured publishing systems that help editors manage content safely without weakening frontend quality.",
    icon: "panels",
    overview: {
      title: "Content systems editors can trust.",
      paragraphs: [
        "I define content models, reusable page patterns, permissions, and editorial controls around the information your organization maintains.",
        "The frontend remains fast and consistent while editors receive useful control instead of an unstructured page builder or a developer-only workflow.",
      ],
    },
    inclusions: [
      ["Content modeling", "Define reusable fields, relationships, validation, and editorial meaning."],
      ["Editorial workflow", "Map roles, review steps, drafts, publishing, and ownership."],
      ["Reusable templates", "Create flexible page patterns that protect content and visual consistency."],
      ["Frontend delivery", "Render structured content through responsive, accessible product components."],
      ["Migration planning", "Separate automated migration from content that needs human review."],
      ["Editor handoff", "Provide practical guidance for publishing and maintaining the system."],
    ],
    technologies: ["django", "strapi", "react", "nuxt", "postgresql", "docker"],
    faqs: [
      ["Do we need a headless CMS?", "Not always. I recommend headless architecture when content serves multiple products or frontend control justifies the added operational complexity."],
      ["Can you migrate existing content?", "Yes. I review content quality, volume, media, relationships, URLs, and redirects before defining what can be automated safely."],
      ["Can different teams have different permissions?", "Yes, when the selected platform supports the required roles and object boundaries. I treat permissions as part of the content model, not an afterthought."],
      ["Will editors receive documentation?", "Yes. The handoff can include field guidance, workflow notes, publishing checks, and focused training for the people who own content."],
    ],
  },
  {
    id: "bug-fixing-responsiveness",
    slug: "bug-fixing-responsiveness",
    title: "Bug Fixing and Responsiveness",
    shortTitle: "Diagnosis and repair",
    summary: "Focused diagnosis and repairs for broken journeys, state, integrations, layouts, and browser behavior.",
    icon: "wrench",
    overview: {
      title: "Find the cause. Fix the right layer.",
      paragraphs: [
        "I reproduce the issue, narrow the affected system, inspect the relevant state and data flow, then define the smallest safe correction.",
        "This is especially useful for established products where a broad rewrite would increase risk and where the team needs a clear explanation of what failed.",
      ],
    },
    inclusions: [
      ["Issue reproduction", "Document the environment, steps, expected behavior, and observable failure."],
      ["Root-cause analysis", "Trace the relevant component, request, state, data, or deployment boundary."],
      ["Responsive repair", "Correct overflow, breakpoints, content edge cases, and touch interactions."],
      ["Browser investigation", "Isolate rendering or behavior differences across supported browsers."],
      ["Integration debugging", "Inspect requests, responses, contracts, authentication, and failure handling."],
      ["Change notes", "Explain the cause, correction, affected areas, and practical verification path."],
    ],
    technologies: ["sentry", "react", "vue", "django", "posthog", "git"],
    faqs: [
      ["What should I send with a bug report?", "Send the affected URL or environment, steps to reproduce, expected behavior, screenshots or logs, browser and device, and when the problem began."],
      ["Can you estimate the fix immediately?", "I can estimate an initial diagnostic pass. A reliable fix estimate usually follows reproduction because similar symptoms can have very different causes."],
      ["Can you debug code you did not build?", "Often, yes. I first review the stack, version, conventions, and available access to confirm the issue is safe and appropriate for me to change."],
      ["Will you rewrite the feature?", "Only when the evidence shows the current boundary cannot be repaired safely. My default is the smallest correction that addresses the root cause."],
    ],
  },
  {
    id: "website-maintenance-security",
    slug: "website-maintenance-security",
    title: "Website Maintenance and Security",
    shortTitle: "Ongoing technical care",
    summary: "Planned updates, monitoring, release support, and security hygiene for websites that need clear ownership.",
    icon: "shield",
    overview: {
      title: "Steady maintenance, fewer surprises.",
      paragraphs: [
        "I help define the updates, checks, access boundaries, release practices, and recovery expectations that keep a web product supportable.",
        "Coverage is based on the platform and business impact. Planned improvements and urgent production issues remain clearly separated so expectations stay realistic.",
      ],
    },
    inclusions: [
      ["Dependency review", "Plan supported library, plugin, framework, and platform updates."],
      ["Security hygiene", "Review configuration, access, validation, secrets, and known vulnerability exposure."],
      ["Monitoring", "Organize availability, error, and performance signals around product impact."],
      ["Backup review", "Check the current backup coverage and whether restore procedures are understood."],
      ["Controlled changes", "Deliver small improvements through a visible and reversible release process."],
      ["Maintenance notes", "Summarize completed work, identified risks, and recommended next actions."],
    ],
    technologies: ["sentry", "docker", "nginx", "aws", "django", "git"],
    faqs: [
      ["What can ongoing maintenance include?", "It can include dependency updates, platform checks, small improvements, release support, and agreed monitoring. I document the exact boundaries before work begins."],
      ["Does maintenance guarantee a site cannot be compromised?", "No one can make that guarantee. Good maintenance reduces avoidable risk through updates, access hygiene, validation, monitoring, and a clear response process."],
      ["Can you take over a site built by another team?", "Yes, after reviewing the codebase, hosting, dependencies, access, backups, and known issues. That review determines whether ongoing support is responsible."],
      ["Can new features be included?", "Small changes may fit. Larger product work is scoped separately so it receives the design, implementation, and verification attention it needs."],
    ],
  },
  {
    id: "speed-optimization-seo",
    slug: "speed-optimization-seo",
    title: "Speed Optimization and SEO",
    shortTitle: "Performance and search",
    summary: "Technical improvements for Core Web Vitals, indexing, search journeys, measurement, and conversion behavior.",
    icon: "gauge",
    overview: {
      title: "Faster pages, clearer search signals.",
      paragraphs: [
        "I review rendering, assets, metadata, structured content, indexation, internal links, and third-party scripts to find the highest-value technical work.",
        "Lighthouse provides a lab starting point. PageSpeed field data, Search Console, PostHog, Hotjar, and business analytics show whether the improvement helps real users and useful search journeys.",
      ],
    },
    inclusions: [
      ["Core Web Vitals", "Inspect LCP, INP, CLS, page groups, and the code or content behind weak signals."],
      ["Rendering and assets", "Review JavaScript, images, fonts, caching, third parties, and delivery strategy."],
      ["Technical SEO", "Check crawlability, indexability, canonicals, redirects, sitemaps, and template behavior."],
      ["On-page structure", "Align titles, descriptions, headings, schema, internal links, and page purpose."],
      ["Behavior analysis", "Use PostHog or Hotjar to understand journeys, friction, and conversion context."],
      ["Priority roadmap", "Group findings into immediate fixes, planned improvements, and longer-term work."],
    ],
    technologies: ["lighthouse", "pagespeed", "searchConsole", "posthog", "hotjar", "ahrefs"],
    faqs: [
      ["Can you guarantee a ranking?", "No. Search results depend on competition, content, authority, technical quality, user value, and search-system changes. I focus on measurable fundamentals and useful journeys."],
      ["Why use both Lighthouse and PageSpeed Insights?", "Lighthouse is a controlled lab audit. PageSpeed can add real-user field data. I use the lab result to investigate and field data to judge production impact."],
      ["Where do PostHog and Hotjar fit?", "Search tools show how people arrive. Product and behavior analytics help explain what they do next, where they struggle, and whether the page supports a useful action."],
      ["Do we need a redesign to improve performance?", "Usually not. Many issues can be addressed through targeted changes to assets, rendering, code delivery, templates, and third-party scripts."],
    ],
  },
];

export function getPortfolioServiceBySlug(slug) {
  return portfolioServiceCatalog.find((service) => service.slug === slug);
}

export function getPortfolioServiceHref(service) {
  return `/portfolio/services/${service.slug}`;
}

export function getServiceTechnologies(service) {
  return service.technologies.map((technologyId) => ({
    id: technologyId,
    ...portfolioTechnologyCatalog[technologyId],
  }));
}
