import { ArrowRight, CalendarClock, CheckCircle2, CircleAlert, Users } from "lucide-react";
import { attentionItems, memberWorkSignal, todayInManila } from "../attention";
import { Button } from "../../personal-dashboard/ui/button";

const MAX_VISIBLE = 5;

function AttentionLink({ href, onNavigate, children, className = "" }) {
  return <a href={href} onClick={(event) => { if (!event.metaKey && !event.ctrlKey && !event.shiftKey && !event.altKey) { event.preventDefault(); onNavigate(); } }} className={`group flex w-full items-start gap-3 rounded-md border p-3 text-left transition-colors hover:brightness-[0.98] active:brightness-95 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 ${className}`}>{children}<ArrowRight size={15} className="mt-1 shrink-0 text-slate-500 transition-transform group-hover:translate-x-0.5 motion-reduce:transition-none" aria-hidden="true"/></a>;
}

export default function AttentionRail({ actions, members, currentWeek, loading, error, retry, navigate }) {
  const today = todayInManila();
  const items = attentionItems(actions, today);
  const people = members.map((member) => ({ member, signal: memberWorkSignal(member, actions, currentWeek, today) })).filter(({ signal }) => ["urgent", "soon"].includes(signal.level)).sort((a, b) => (a.signal.level === "urgent" ? 0 : 1) - (b.signal.level === "urgent" ? 0 : 1) || a.member.name.localeCompare(b.member.name));
  return <aside aria-label="Recorded work needing attention" className="min-w-0 self-start rounded-md border bg-white">
    <div className="border-b p-4"><div className="flex items-center gap-2"><CircleAlert size={18} className="text-rose-700" aria-hidden="true"/><h2 className="text-base font-semibold text-slate-950">Needs attention</h2></div><p className="mt-1 text-xs leading-5 text-slate-600">Blocked, overdue, or due within two days. Based only on saved work.</p></div>
    {loading ? <div className="space-y-2 p-4" aria-busy="true" aria-label="Loading attention items">{[0, 1, 2].map((item) => <div key={item} className="h-16 animate-pulse rounded-md bg-slate-100"/>)}</div> : error ? <div className="p-4"><p role="alert" className="text-sm text-rose-800">Could not load attention items. {error}</p><Button variant="outline" size="sm" className="mt-2" onClick={retry}>Try again</Button></div> : <>
      <section aria-labelledby="attention-actions-title" className="p-4"><div className="mb-3 flex items-center justify-between gap-2"><h3 id="attention-actions-title" className="text-sm font-semibold text-slate-900">Actions</h3><span className="text-xs tabular-nums text-slate-600">{items.length}</span></div>{items.length ? <div className="space-y-2">{items.slice(0, MAX_VISIBLE).map(({ action, level, reason }) => <AttentionLink key={action.id} href={`/business/roadmap?action=${action.id}`} onNavigate={() => navigate(`roadmap?action=${action.id}`)} className={level === "urgent" ? "border-rose-200 bg-rose-50/60" : "border-amber-200 bg-amber-50/60"}><span className={`grid size-8 shrink-0 place-items-center rounded-full ${level === "urgent" ? "bg-rose-100 text-rose-800" : "bg-amber-100 text-amber-800"}`}>{level === "urgent" ? <CircleAlert size={17} aria-hidden="true"/> : <CalendarClock size={17} aria-hidden="true"/>}</span><span className="min-w-0 flex-1"><span className="block break-words text-sm font-medium text-slate-950">{action.title}</span><span className={`mt-0.5 block text-xs font-medium ${level === "urgent" ? "text-rose-800" : "text-amber-900"}`}>{reason}{action.owner ? ` · ${members.find((member) => member.id === action.owner)?.name || "Assigned"}` : ""}</span></span></AttentionLink>)}{items.length > MAX_VISIBLE && <Button variant="link" className="px-0" onClick={() => navigate("roadmap")}>View all {items.length} in the 90-Day Plan <ArrowRight size={14}/></Button>}</div> : <p className="flex items-center gap-2 rounded-md border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900"><CheckCircle2 size={17} className="shrink-0" aria-hidden="true"/> No blocked or approaching actions.</p>}</section>
      <section aria-labelledby="attention-people-title" className="border-t p-4"><div className="mb-3 flex items-center justify-between gap-2"><h3 id="attention-people-title" className="flex items-center gap-2 text-sm font-semibold text-slate-900"><Users size={16} className="text-blue-700" aria-hidden="true"/> Team follow-up</h3><span className="text-xs tabular-nums text-slate-600">{people.length}</span></div>{people.length ? <div className="space-y-2">{people.slice(0, MAX_VISIBLE).map(({ member, signal }) => <AttentionLink key={member.id} href={`/business/team/${member.id}`} onNavigate={() => navigate(`team/${member.id}`)} className={signal.level === "urgent" ? "border-rose-200 bg-rose-50/60" : "border-amber-200 bg-amber-50/60"}><span className={`grid size-8 shrink-0 place-items-center rounded-full text-xs font-semibold ${signal.level === "urgent" ? "bg-rose-100 text-rose-800" : "bg-amber-100 text-amber-900"}`}>{member.name.split(/\s+/).map((part) => part[0]).slice(0, 2).join("").toUpperCase()}</span><span className="min-w-0 flex-1"><span className="block break-words text-sm font-medium text-slate-950">{member.name}</span><span className={`mt-0.5 block text-xs ${signal.level === "urgent" ? "text-rose-800" : "text-amber-900"}`}>{signal.title} · {signal.detail}</span></span></AttentionLink>)}{people.length > MAX_VISIBLE && <Button variant="link" className="px-0" onClick={() => navigate("team")}>View team development <ArrowRight size={14}/></Button>}</div> : <p className="text-sm text-slate-600">No team member has blocked or approaching assigned work.</p>}</section>
    </>}
  </aside>;
}
