# Generated by Django 5.2.17 on 2026-09-27 10:11

from django.conf import settings
from django.db import migrations, models


def preserve_occurrence_dates(apps, schema_editor):
    apps.get_model("finance", "Transaction").objects.using(schema_editor.connection.alias).filter(schedule__isnull=False).update(scheduled_date=models.F("date"))


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='finance_income_occurrence',
        ),
        migrations.AddField(
            model_name='transaction',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(preserve_occurrence_dates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('schedule', 'scheduled_date'), name='finance_income_occurrence'),
        ),
    ]
