import { useLayoutEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, Check, ClipboardList, Copy, FileText, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import ApplicationPageShell from "../application/ApplicationPageShell";

const stages = [
  { id: "inquiry", title: "01 · Inquiry", intro: "Understand the request before naming a price.", tasks: ["Record the contact and organization.", "Ask who approves the budget and the work.", "Book a discovery conversation and agree on the next contact step."] },
  { id: "discovery", title: "02 · Discovery", intro: "Map the real process, not just the tool the client imagines.", tasks: ["Walk through the current workflow from start to finish.", "Ask how often it runs, how long it takes, and who touches it.", "List existing tools, subscriptions, sample data, edge cases, and failure handling.", "Define a measurable success outcome and the decision-maker."] },
  { id: "recap", title: "03 · Recap", intro: "Check that you and the client mean the same thing.", tasks: ["Summarize the present problem and desired outcome in plain language.", "List assumptions, exclusions, risks, and unanswered questions.", "Ask the client to correct or confirm the recap before scoping work."] },
  { id: "proposal", title: "04 · Proposal", intro: "Describe the outcome and boundaries, not a wall of jargon.", tasks: ["Define deliverables and what is explicitly out of scope.", "Set phases, dependencies, client responsibilities, and target timing.", "Quote in an agreed currency and propose milestone amounts and dates."] },
  { id: "agreement", title: "05 · Agreement & initial payment", intro: "Use terms suited to the project and the parties' jurisdictions.", tasks: ["Have the agreement draft reviewed for the relevant law and risk.", "Agree on revision limits, change-request handling, third-party costs, ownership, and support.", "Record signatures and payment status manually before kickoff."] },
  { id: "access", title: "06 · Access & kickoff", intro: "Collect only the access needed to deliver safely.", tasks: ["Ask for a dedicated role or collaborator account rather than a shared password.", "Confirm who owns subscriptions and external services.", "Use a secure channel for API keys; do not paste secrets into project notes.", "Agree on one contact, an approval path, and realistic test data."] },
  { id: "build", title: "07 · Build & review", intro: "Show progress before the final day.", tasks: ["Send a short done / next / blocked update at an agreed cadence.", "Demo an intermediate version and capture feedback.", "Describe out-of-scope changes and their price/timeline effect before work starts.", "Test the agreed deliverables with the client."] },
  { id: "handover", title: "08 · Handover", intro: "Leave the client able to operate what you built.", tasks: ["Provide user instructions, technical notes, and a walkthrough.", "Confirm access ownership and the agreed support start and end dates.", "Record completion and final invoice status."] },
  { id: "support", title: "09 · Support & close", intro: "Keep the support boundary explicit.", tasks: ["Log issues against the agreed support terms.", "Separate defects from new requests without assuming either is billable.", "Confirm completion and close the project manually."] },
];

const outlines = [
  { title: "Discovery questions", body: `Client: [name]\nProject: [working title]\n\n1. Walk me through the current process, from start to finish.\n2. How often does it happen, and how long does each run take?\n3. Who does the work, checks it, and approves a change?\n4. Which tools, subscriptions, accounts, and data are involved?\n5. What would a successful result look like?\n6. What happens when something fails?\n7. Who approves the budget and the final work?\n\nOpen questions: [notes]` },
  { title: "Recap email outline", body: `Subject: Recap of [project]\n\nHi [name],\n\nHere is my understanding of your current process: [brief summary].\nThe outcome you want is: [specific outcome].\n\nAssumptions: [list]\nQuestions to resolve: [list]\nNot included at this stage: [list]\n\nPlease correct anything I have misunderstood. Once we agree on this, I can prepare a proposal.\n\nThanks,\n[your name]` },
  { title: "Proposal outline", body: `Project: [working title]\nClient: [name]\n\nOutcome: [what changes for the client]\nDeliverables: [specific outputs]\nOut of scope: [clear exclusions]\nPhases and target dates: [timeline]\nClient dependencies: [access, data, approvals]\nPrice and currency: [amount and currency]\nProposed milestones: [amount and due point for each]\nAcceptance approach: [how work will be reviewed]\nOpen questions: [list]` },
];

function CopyOutline({ title, body }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try { await navigator.clipboard.writeText(`${title}\n\n${body}`); setCopied(true); window.setTimeout(() => setCopied(false), 2500); }
    catch { setCopied(false); }
  };
  return <section className="border-t border-slate-200 pt-7"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="portfolio-display text-2xl font-semibold tracking-[-0.025em] text-slate-950">{title}</h3><button type="button" onClick={copy} className="inline-flex items-center gap-2 rounded-md border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700 transition hover:border-blue-300 hover:text-[#2448d8] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#2f5bff]">{copied ? <Check size={16}/> : <Copy size={16}/>}{copied ? "Copied" : "Copy outline"}</button></div><pre className="mt-5 overflow-x-auto whitespace-pre-wrap rounded-lg border border-slate-200 bg-slate-50 p-5 font-mono text-sm leading-6 text-slate-700">{body}</pre></section>;
}

function CopyChecklist({ stage }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(`${stage.title}\n${stage.tasks.map((task) => `- [ ] ${task}`).join("\n")}`);
      setCopied(true); window.setTimeout(() => setCopied(false), 2500);
    } catch { setCopied(false); }
  };
  return <button type="button" onClick={copy} className="inline-flex shrink-0 items-center gap-2 rounded-md border border-slate-200 bg-white px-3 py-1.5 text-sm font-semibold text-slate-700 transition hover:border-blue-300 hover:text-[#2448d8] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#2f5bff]">{copied ? <Check size={15}/> : <Copy size={15}/>}{copied ? "Copied" : "Copy checklist"}</button>;
}

export default function ClientWorkflowGuidePage() {
  useLayoutEffect(() => { window.scrollTo(0, 0); }, []);
  return <ApplicationPageShell title="A practical client project workflow" description="A reusable nine-stage checklist for scoping, building, and handing over software or automation projects." canonicalPath="/portfolio/how-tos/client-workflow" type="article"><article>
    <header className="border-b border-slate-200 bg-white px-5 pb-14 pt-32 sm:px-8 sm:pb-16 sm:pt-40"><div className="mx-auto max-w-5xl"><Link to="/portfolio/how-tos" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 transition hover:text-[#2448d8] focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-[#2f5bff]"><ArrowLeft size={16}/>All how-tos</Link><h1 className="portfolio-display mt-8 max-w-4xl text-balance text-5xl font-semibold tracking-[-0.04em] text-slate-950 sm:text-6xl">A practical client project workflow</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-slate-600">From the first inquiry to support handoff: the checkpoints I use to keep software and AI-automation work clear for both sides.</p><div className="mt-8 flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-slate-200 pt-5 text-sm text-slate-500"><span className="font-semibold text-slate-900">Mico Ang</span><span>Client delivery</span><span>Reusable checklist</span></div></div></header>
    <div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 sm:py-20 lg:grid-cols-[13rem_minmax(0,48rem)] lg:justify-center lg:gap-16"><nav aria-label="On this page" className="h-fit border-t border-slate-300 pt-5 text-sm lg:sticky lg:top-28"><p className="font-semibold text-slate-950">On this page</p><a href="#workflow" className="mt-4 block text-slate-600 hover:text-[#2448d8]">Nine stages</a><a href="#outlines" className="mt-3 block text-slate-600 hover:text-[#2448d8]">Copyable outlines</a><a href="#boundaries" className="mt-3 block text-slate-600 hover:text-[#2448d8]">Important boundaries</a></nav><div className="min-w-0 text-lg leading-8 text-slate-700"><p>The sequence is a guide, not a gate. A real engagement may revisit discovery, pause for an approval, or change scope. I keep client contacts, project-specific documents, payment reports, and access notes in a private workspace; this page is only the general process.</p>
    <section id="workflow" className="mt-12 scroll-mt-28"><div className="flex items-center gap-3 text-[#2448d8]"><ClipboardList size={25} strokeWidth={1.7}/><h2 className="portfolio-display text-3xl font-semibold tracking-[-0.03em] text-slate-950 sm:text-4xl">The nine stages</h2></div><div className="mt-7 border-t border-slate-300">{stages.map((stage) => <section key={stage.id} id={stage.id} className="scroll-mt-28 border-b border-slate-200 py-8"><div className="flex flex-wrap items-start justify-between gap-3"><h3 className="portfolio-display text-2xl font-semibold tracking-[-0.025em] text-slate-950">{stage.title}</h3><CopyChecklist stage={stage}/></div><p className="mt-2 text-slate-600">{stage.intro}</p><ul className="mt-5 space-y-3">{stage.tasks.map((task) => <li key={task} className="flex items-start gap-3"><Check size={18} className="mt-1.5 shrink-0 text-[#2448d8]" aria-hidden="true"/><span>{task}</span></li>)}</ul></section>)}</div></section>
    <section id="outlines" className="mt-16 scroll-mt-28"><div className="flex items-center gap-3 text-[#2448d8]"><FileText size={25} strokeWidth={1.7}/><h2 className="portfolio-display text-3xl font-semibold tracking-[-0.03em] text-slate-950 sm:text-4xl">Starting outlines</h2></div><p className="mt-5">Copy these blank prompts, then tailor every line to the actual engagement. They are not emails sent by this site.</p><div className="mt-7 space-y-8">{outlines.map((outline) => <CopyOutline key={outline.title} {...outline}/>)}</div></section>
    <section id="boundaries" className="mt-16 scroll-mt-28 border-t border-slate-200 pt-14"><div className="flex items-center gap-3 text-[#2448d8]"><ShieldCheck size={25} strokeWidth={1.7}/><h2 className="portfolio-display text-3xl font-semibold tracking-[-0.03em] text-slate-950 sm:text-4xl">Important boundaries</h2></div><p className="mt-5">No deposit percentage, revision count, support term, or law should be copied into an agreement simply because it appears in someone else's process. Those are decisions for the actual client, project, and jurisdiction. Have a qualified professional review contract language when appropriate.</p><p className="mt-5">Never put passwords or raw API keys in a client checklist. Record the secure handoff method and who owns the account instead. A “paid” status in a work tracker is a manual report, not proof that funds cleared.</p><p className="mt-5 text-base">This workflow was adapted from <a href="https://www.facebook.com/taraaicommunity/videos/1415689260539517/" target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 font-semibold text-[#2448d8] underline decoration-blue-200 underline-offset-4 hover:decoration-[#2f5bff]">Tara AI Community's client-onboarding video<ArrowUpRight size={15}/></a> and refined for software delivery. The templates above are my general outlines, not a transcript or legal advice.</p></section><Link to="/portfolio/how-tos" className="mt-14 inline-flex items-center gap-2 text-sm font-semibold text-[#2448d8] hover:underline"><ArrowLeft size={16}/>All how-tos</Link></div></div>
  </article></ApplicationPageShell>;
}
